module.exports = {
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-config-property-sort-order-smacss",
  ],
  "plugins": ["stylelint-scss", "stylelint-prettier"],
  "rules": {
    "selector-class-pattern":
      "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",
    "rule-empty-line-before": [
      "always",
      {
        "except": [
          "after-rule",
          "after-single-line-comment",
          "inside-block-and-after-rule",
          "inside-block",
          "first-nested",
        ],
      },
    ],
    "selector-pseudo-element-colon-notation": "single",
    "at-rule-empty-line-before": [
      "always",
      { "except": ["after-same-name", "inside-block"] },
    ],
    "at-rule-disallowed-list": ["debug"],
    "at-rule-no-unknown": null,
    "at-rule-no-vendor-prefix": true,
    "block-no-empty": true,
    "color-hex-length": "short",
    "color-named": ["always-where-possible"],
    "color-no-invalid-hex": true,
    "declaration-block-single-line-max-declarations": 1,
    "declaration-empty-line-before": [
      "never",
      { "ignore": ["after-declaration"] },
    ],
    "declaration-property-value-disallowed-list": {
      "border": ["0"],
      "border-top": ["0"],
      "border-right": ["0"],
      "border-bottom": ["0"],
      "border-left": ["0"],
    },
    "function-url-quotes": "always",
    "length-zero-no-unit": true,
    "max-nesting-depth": [
      3,
      { "ignoreAtRules": ["each", "media", "supports", "include"] },
    ],
    "media-feature-name-no-vendor-prefix": true,
    "order/order": [
      [
        "custom-properties",
        "dollar-variables",
        { "type": "at-rule", "name": "extend" },
        { "type": "at-rule", "name": "include", "hasBlock": false },
        "declarations",
        { "type": "at-rule", "name": "include", "hasBlock": true },
        "rules",
      ],
    ],
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "scss/at-extend-no-missing-placeholder": true,
    "scss/at-function-pattern": "^[a-z]+([a-z0-9-]+[a-z0-9]+)?$",
    "scss/load-no-partial-leading-underscore": true,
    "scss/at-import-partial-extension-disallowed-list": ["scss"],
    "scss/at-mixin-pattern": "^[a-z]+([a-z0-9-]+[a-z0-9]+)?$",
    "scss/at-rule-no-unknown": true,
    "scss/dollar-variable-colon-space-after": "always",
    "scss/dollar-variable-colon-space-before": "never",
    "scss/dollar-variable-pattern": "^[_]?[a-z]+([a-z0-9-]+[a-z0-9]+)?$",
    "scss/percent-placeholder-pattern": "^[a-z]+([a-z0-9-]+[a-z0-9]+)?$",
    "scss/selector-no-redundant-nesting-selector": true,
    "selector-max-compound-selectors": 3,
    "selector-max-id": 0,
    "selector-no-qualifying-type": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-element-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "value-no-vendor-prefix": true,
    "scss/dollar-variable-empty-line-after": [
      "always",
      { "except": ["before-dollar-variable"] },
    ],
    "no-descending-specificity": null,
    "prettier/prettier": true,
  },
};
